#!/usr/bin/env python3
"""
Prefab 生成器

从 Prefab 文档生成 Unity C# 脚本，可通过 Unity 命令行自动执行
"""

import sys
import os
from pathlib import Path
from parse_prefab_doc import parse_prefab_document, GameObject
from component_rules import get_components_for_node, get_required_namespaces


class CSharpCodeGenerator:
    """C# 代码生成器"""

    def __init__(self, prefab_name: str):
        self.prefab_name = prefab_name
        self.code_lines = []
        self.indent_level = 0
        self.variable_counter = 0
        self.node_variables = {}  # GameObject -> 变量名映射

    def add_line(self, line: str = ""):
        """添加一行代码"""
        if line:
            indent = "    " * self.indent_level
            self.code_lines.append(f"{indent}{line}")
        else:
            self.code_lines.append("")

    def indent(self):
        """增加缩进"""
        self.indent_level += 1

    def dedent(self):
        """减少缩进"""
        self.indent_level = max(0, self.indent_level - 1)

    def get_variable_name(self, node: GameObject) -> str:
        """获取节点的变量名"""
        if node in self.node_variables:
            return self.node_variables[node]

        # 清理名称中的特殊字符
        # 例如: "Text (TMP)" -> "Text_TMP", "img_reward" -> "img_reward"
        clean_name = node.name.replace(' ', '_').replace('(', '').replace(')', '').replace('-', '_')

        # 生成变量名（小驼峰）
        # 例如: img_reward -> imgReward, Text_TMP -> textTmp
        name_parts = clean_name.split('_')
        name_parts = [p for p in name_parts if p]  # 移除空字符串

        if len(name_parts) > 1:
            var_name = name_parts[0].lower() + ''.join(p.capitalize() for p in name_parts[1:])
        elif len(name_parts) == 1:
            var_name = name_parts[0][0].lower() + name_parts[0][1:] if len(name_parts[0]) > 1 else name_parts[0].lower()
        else:
            var_name = "gameObject"

        # 避免关键字冲突
        if var_name in ['object', 'string', 'int', 'float', 'bool', 'void', 'event']:
            var_name = f"go{var_name.capitalize()}"

        # 确保唯一性
        base_var_name = var_name
        counter = 1
        while var_name in self.node_variables.values():
            var_name = f"{base_var_name}{counter}"
            counter += 1

        self.node_variables[node] = var_name
        return var_name

    def generate_create_node(self, node: GameObject):
        """生成创建节点的代码"""
        var_name = self.get_variable_name(node)

        # 创建 GameObject
        self.add_line(f"GameObject {var_name} = new GameObject(\"{node.name}\");")

        # 获取需要添加的组件
        comp_info = get_components_for_node(node.name, node.components)

        # 添加组件
        for component in comp_info["components"]:
            self.add_line(f"{var_name}.AddComponent<{component}>();")

        # 设置父子关系
        if node.parent:
            parent_var = self.get_variable_name(node.parent)
            self.add_line(f"{var_name}.transform.SetParent({parent_var}.transform, false);")

        self.add_line()

        # 递归创建子节点
        for child in node.children:
            self.generate_create_node(child)

    def generate(self, hierarchy):
        """生成完整的 C# 脚本"""
        # 收集所有需要的组件
        all_components = set()
        for node in hierarchy.all_nodes:
            comp_info = get_components_for_node(node.name, node.components)
            all_components.update(comp_info["components"])

        # 获取需要的命名空间
        namespaces = get_required_namespaces(all_components)

        # 生成 using 语句
        for ns in sorted(namespaces):
            self.add_line(f"using {ns};")
        self.add_line()

        # 生成类
        class_name = f"Create{self.prefab_name}"
        self.add_line("/// <summary>")
        self.add_line(f"/// Auto-generated Prefab builder for {self.prefab_name}")
        self.add_line("/// Generated by blockgame-prefab-builder skill")
        self.add_line("/// </summary>")
        self.add_line(f"public class {class_name}")
        self.add_line("{")
        self.indent()

        # 生成 CreatePrefab 静态方法
        self.add_line("[MenuItem(\"Tools/Create Prefab/" + self.prefab_name + "\")]")
        self.add_line("public static void CreateFromMenu()")
        self.add_line("{")
        self.indent()
        self.add_line("CreatePrefab();")
        self.dedent()
        self.add_line("}")
        self.add_line()

        # 生成主方法（可被命令行调用）
        self.add_line("public static void CreatePrefab()")
        self.add_line("{")
        self.indent()

        self.add_line(f"Debug.Log(\"Creating prefab: {self.prefab_name}\");")
        self.add_line()

        # 生成创建 GameObject 的代码
        self.generate_create_node(hierarchy.root)

        # 保存为 Prefab
        root_var = self.get_variable_name(hierarchy.root)
        output_dir = "Assets/Generated/Prefabs"
        output_path = f"{output_dir}/{self.prefab_name}.prefab"

        self.add_line("// 确保输出目录存在")
        self.add_line(f"string outputDir = \"{output_dir}\";")
        self.add_line("if (!AssetDatabase.IsValidFolder(outputDir))")
        self.add_line("{")
        self.indent()
        self.add_line("System.IO.Directory.CreateDirectory(outputDir);")
        self.add_line("AssetDatabase.Refresh();")
        self.dedent()
        self.add_line("}")
        self.add_line()

        self.add_line("// 保存为 Prefab")
        self.add_line(f"string outputPath = \"{output_path}\";")
        self.add_line(f"PrefabUtility.SaveAsPrefabAsset({root_var}, outputPath);")
        self.add_line()

        self.add_line("// 清理场景中的临时对象")
        self.add_line(f"Object.DestroyImmediate({root_var});")
        self.add_line()

        self.add_line(f"Debug.Log($\"✅ Prefab created: {{outputPath}}\");")

        self.dedent()
        self.add_line("}")

        self.dedent()
        self.add_line("}")

        return '\n'.join(self.code_lines)


def generate_prefab_script(doc_path: str, output_path: str = None) -> str:
    """
    从文档生成 Prefab 创建脚本

    Args:
        doc_path: Prefab 文档路径
        output_path: 输出 C# 脚本路径（可选）

    Returns:
        生成的 C# 代码
    """
    # 解析文档
    print(f"📖 解析文档: {doc_path}")
    hierarchy = parse_prefab_document(doc_path)
    print(f"✅ 解析成功: {hierarchy.prefab_name} ({len(hierarchy.all_nodes)} 节点)")

    # 生成代码
    print(f"🔧 生成 C# 脚本...")
    generator = CSharpCodeGenerator(hierarchy.prefab_name)
    code = generator.generate(hierarchy)

    # 确定输出路径
    if not output_path:
        output_dir = Path("Assets/Editor/Generated")
        output_dir.mkdir(parents=True, exist_ok=True)
        output_path = output_dir / f"Create{hierarchy.prefab_name}.cs"
    else:
        output_path = Path(output_path)
        output_path.parent.mkdir(parents=True, exist_ok=True)

    # 写入文件
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(code)

    print(f"✅ 脚本已生成: {output_path}")
    print(f"📊 代码行数: {len(code.splitlines())}")

    return str(output_path)


def main():
    """主函数"""
    if len(sys.argv) < 2:
        print("Usage: python3 generate_prefab.py <prefab_doc_path> [output_script_path]")
        print("\nExample:")
        print("  python3 generate_prefab.py \\")
        print("      ../blockgame-scene-reference/references/Prefab_CommonRewardPopup_Hierarchy.md")
        print("\n  python3 generate_prefab.py \\")
        print("      ../blockgame-scene-reference/references/Prefab_Settings_Hierarchy.md \\")
        print("      Assets/Editor/Generated/CreateSettings.cs")
        sys.exit(1)

    doc_path = sys.argv[1]
    output_path = sys.argv[2] if len(sys.argv) > 2 else None

    try:
        script_path = generate_prefab_script(doc_path, output_path)
        print(f"\n📝 下一步:")
        print(f"1. 在 Unity Editor 中:")
        print(f"   菜单: Tools → Create Prefab → [Prefab名称]")
        print(f"\n2. 或通过命令行自动执行:")
        print(f"   /Applications/Unity/Hub/Editor/<version>/Unity.app/Contents/MacOS/Unity \\")
        print(f"     -quit -batchmode -projectPath $(pwd) \\")
        print(f"     -executeMethod Create{Path(script_path).stem[6:]}.CreatePrefab")

    except Exception as e:
        print(f"❌ 生成失败: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)


if __name__ == "__main__":
    main()
